[debug] [2025-10-25T07:59:15.210Z] ----------------------------------------------------------------------
[debug] [2025-10-25T07:59:15.213Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\kibox\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2025-10-25T07:59:15.214Z] CLI Version:   14.22.0
[debug] [2025-10-25T07:59:15.214Z] Platform:      win32
[debug] [2025-10-25T07:59:15.214Z] Node Version:  v22.17.0
[debug] [2025-10-25T07:59:15.214Z] Time:          Sat Oct 25 2025 13:29:15 GMT+0530 (India Standard Time)
[debug] [2025-10-25T07:59:15.214Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-10-25T07:59:15.216Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  E:\saeds website\frontend

[debug] [2025-10-25T07:59:16.205Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-10-25T07:59:16.205Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2025-10-25T08:00:08.552Z] ExitPromptError: User force closed the prompt with SIGINT
    at Interface.sigint (C:\Users\kibox\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\@inquirer\core\dist\commonjs\lib\create-prompt.js:101:37)
    at Interface.emit (node:events:518:28)
    at Interface.emit (node:domain:489:12)
    at [_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1132:18)
    at ReadStream.onkeypress (node:internal/readline/interface:271:20)
    at ReadStream.emit (node:events:530:35)
    at ReadStream.emit (node:domain:489:12)
    at emitKeys (node:internal/readline/utils:370:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:64:36)
[error] 
[error] Error: An unexpected error has occurred.
